apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jyxjkowno-nodejs 
  janus-idp.io/tekton: jyxjkowno-nodejs
  backstage.io/kubernetes-id: jyxjkowno-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jyxjkowno-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  